version: "3.9"
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_NODENAME: thuusbezorgd-rabbitmq-node
    volumes:
      - ./development/rabbitmq/data/:/var/lib/rabbitmq/
  pg:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/pg/init:/docker-entrypoint-initdb.d/
      - ./raw:/raw
      - ./db/pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1q2w3e!
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "127.0.0.1:9091:80"
    volumes:
      - ./db/pg:/db
    environment:
      PGADMIN_DEFAULT_EMAIL: student@hu.nl
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e!
      PGADMIN_SERVER_JSON_FILE: /db/server.json